"""Control plane API — exposes Gmail and Calendar operations over HTTP.

We mean "control plane" in the following sense: https://browser-use.com/posts/two-ways-to-sandbox-agents

Runs in render. Holds Google OAuth tokens
and provides authenticated endpoints that the sandbox agent calls.

Session tokens are short-lived credentials that map to a user's Google
OAuth credentials. They are generated by the orchestrator (run_e2b.py)
and passed into the sandbox as an env var.
"""

import base64
import json
import logging
import secrets
import time
from datetime import datetime

from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException, Request
from pydantic import BaseModel

from scheduler.auth.google_auth import load_credentials
from scheduler.calendar.client import CalendarClient, Event
from scheduler.config import config
from scheduler.gmail.client import GmailClient

logger = logging.getLogger(__name__)

app = FastAPI(title="Scheduler Control Plane")

# --- Session store ---

sessions: dict[str, dict] = {}


def register_session(session_token: str, user_id: str) -> None:
    """Register a session with Google credentials for a user.

    Loads credentials from the database if DATABASE_URL is set and the user
    exists. Falls back to local OAuth flow (token.json) for development.
    """
    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    calendar.get_or_create_stash_calendar()

    sessions[session_token] = {
        "user_id": user_id,
        "gmail": gmail,
        "calendar": calendar,
        "created_at": time.time(),
    }



def get_session(authorization: str = Header()) -> dict:
    """Validate the session token from the Authorization header."""
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid authorization header")

    token = authorization.removeprefix("Bearer ")
    session = sessions.get(token)
    if not session:
        raise HTTPException(status_code=401, detail="Invalid or expired session token")

    return session


# --- Serialization helpers ---


def _serialize_email(email) -> dict:
    return {
        "id": email.id,
        "thread_id": email.thread_id,
        "sender": email.sender,
        "recipient": email.recipient,
        "subject": email.subject,
        "body": email.body,
        "date": email.date.isoformat(),
        "snippet": email.snippet,
    }


def _serialize_event(event) -> dict:
    return {
        "id": event.id,
        "summary": event.summary,
        "start": event.start.isoformat(),
        "end": event.end.isoformat(),
        "description": event.description,
    }


# --- Request models ---


class SearchEmailsRequest(BaseModel):
    query: str
    max_results: int = 50


class CreateDraftRequest(BaseModel):
    thread_id: str
    to: str
    subject: str
    body: str


class GetEventsRequest(BaseModel):
    start_date: str
    end_date: str
    include_primary: bool = True


class FindEventRequest(BaseModel):
    summary: str
    start_date: str
    end_date: str


class AddEventRequest(BaseModel):
    summary: str
    start: str
    end: str
    description: str = ""


class UpdateBrandingRequest(BaseModel):
    enabled: bool


class WriteGuideRequest(BaseModel):
    name: str
    content: str


# --- Gmail routes ---


@app.post("/api/v1/gmail/search")
def gmail_search(req: SearchEmailsRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    emails = gmail.search(query=req.query, max_results=req.max_results)
    return {"emails": [_serialize_email(e) for e in emails]}


@app.get("/api/v1/gmail/thread/{thread_id}")
def gmail_thread(thread_id: str, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    messages = gmail.get_thread(thread_id)
    return {"messages": [_serialize_email(e) for e in messages]}


@app.post("/api/v1/gmail/draft")
def gmail_draft(req: CreateDraftRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    draft_id = gmail.create_draft(
        thread_id=req.thread_id, to=req.to, subject=req.subject, body=req.body
    )
    return {"draft_id": draft_id}


# --- Calendar routes ---


@app.post("/api/v1/calendar/events")
def calendar_events(req: GetEventsRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    events = calendar.get_all_events(
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
        include_primary=req.include_primary,
    )
    return {"events": [_serialize_event(e) for e in events]}


@app.post("/api/v1/calendar/find")
def calendar_find(req: FindEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = calendar.find_event(
        summary=req.summary,
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
    )
    if event:
        return {"exists": True, "event": _serialize_event(event)}
    return {"exists": False, "event": None}


@app.post("/api/v1/calendar/add")
def calendar_add(req: AddEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = Event(
        id=None,
        summary=req.summary,
        start=datetime.fromisoformat(req.start),
        end=datetime.fromisoformat(req.end),
        description=req.description,
        source="gmail",
    )
    event_id = calendar.add_event(event)
    return {"event_id": event_id, "status": "created"}


# --- Settings routes ---


@app.get("/api/v1/settings/branding")
def settings_branding_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"stash_branding_enabled": user.stash_branding_enabled}


@app.put("/api/v1/settings/branding")
def settings_branding_put(req: UpdateBrandingRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_stash_branding

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_stash_branding(session["user_id"], req.enabled)
    return {"stash_branding_enabled": req.enabled}


# --- Guide routes ---


class ReadGuideRequest(BaseModel):
    name: str


@app.post("/api/v1/guides/write")
def guides_write(req: WriteGuideRequest, session: dict = Depends(get_session)):
    from scheduler.db import upsert_guide

    user_id = session["user_id"]
    guide = upsert_guide(user_id=user_id, name=req.name, content=req.content)
    return {"status": "written", "guide_id": str(guide.id)}


@app.post("/api/v1/guides/read")
def guides_read(req: ReadGuideRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_guide

    user_id = session["user_id"]
    guide = get_guide(user_id=user_id, name=req.name)
    if not guide:
        raise HTTPException(status_code=404, detail=f"Guide '{req.name}' not found")
    return {"name": guide.name, "content": guide.content, "updated_at": guide.updated_at.isoformat()}


# --- Gmail webhook ---


def _process_new_messages(user_id: str, email_address: str, history_id: str) -> None:
    """Background task: fetch new messages since last history ID and log them.

    This is the hook point where the classifier agent will be triggered.
    """
    from scheduler.db import get_user_by_id, update_gmail_history_id

    user = get_user_by_id(user_id)
    if not user or not user.gmail_history_id:
        # First notification — just store the history ID baseline
        update_gmail_history_id(user_id, history_id)
        logger.info("gmail_webhook: stored initial history_id=%s for user=%s", history_id, email_address)
        return

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)

    try:
        new_message_ids = gmail.get_history(user.gmail_history_id)
    except Exception:
        # History ID may be too old (> 7 days). Reset baseline.
        logger.warning("gmail_webhook: history expired for user=%s, resetting", email_address)
        update_gmail_history_id(user_id, history_id)
        return

    update_gmail_history_id(user_id, history_id)

    if not new_message_ids:
        return

    logger.info(
        "gmail_webhook: %d new message(s) for user=%s: %s",
        len(new_message_ids),
        email_address,
        new_message_ids,
    )

    # TODO: trigger classifier agent for each new message
    # for message_id in new_message_ids:
    #     classify_and_process(user_id, message_id)


@app.post("/webhooks/gmail")
async def gmail_webhook(request: Request, background_tasks: BackgroundTasks):
    """Receive Gmail push notifications via Google Cloud Pub/Sub.

    Google sends a POST with a Pub/Sub message whose data is a base64-encoded
    JSON object containing the user's email address and the latest historyId.

    This endpoint is unauthenticated — Google does not send a session token.
    We look up the user by email address instead.
    """
    from scheduler.db import get_user_by_email

    body = await request.json()
    message = body.get("message", {})
    data_b64 = message.get("data", "")

    if not data_b64:
        raise HTTPException(status_code=400, detail="Missing message data")

    try:
        payload = json.loads(base64.urlsafe_b64decode(data_b64))
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid message data")

    email_address = payload.get("emailAddress")
    history_id = str(payload.get("historyId", ""))

    if not email_address or not history_id:
        raise HTTPException(status_code=400, detail="Missing emailAddress or historyId")

    user = get_user_by_email(email_address)
    if not user:
        logger.warning("gmail_webhook: unknown email %s", email_address)
        # Return 200 so Pub/Sub doesn't retry for unknown users
        return {"status": "ignored", "reason": "unknown user"}

    background_tasks.add_task(_process_new_messages, str(user.id), email_address, history_id)

    return {"status": "ok"}


@app.post("/api/v1/gmail/watch/renew")
def gmail_watch_renew():
    """Renew Gmail push notification watches for all users.

    Intended to be called by a daily cron job. No auth required since
    it only re-registers existing watches (idempotent and safe).
    """
    from scheduler.gmail.watch import renew_all_watches

    result = renew_all_watches()
    return result
