"""Control plane API — exposes Gmail and Calendar operations over HTTP.

We mean "control plane" in the following sense: https://browser-use.com/posts/two-ways-to-sandbox-agents

Runs in render. Holds Google OAuth tokens
and provides authenticated endpoints that the sandbox agent calls.

Session tokens are short-lived credentials that map to a user's Google
OAuth credentials. They are generated by the orchestrator (run_e2b.py)
and passed into the sandbox as an env var.
"""

import asyncio
import base64
import html
import hashlib
import hmac
import json
import logging
import secrets
import threading
import time
import urllib.parse
from contextlib import asynccontextmanager
from datetime import datetime, timezone

import jwt
from jwt import PyJWKClient
from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from pydantic import BaseModel

from scheduler.auth.google_auth import SCOPES, load_credentials
from scheduler.calendar.client import CalendarClient, Event
from scheduler.config import config
from scheduler.gmail.client import GmailClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

_WATCH_RENEWAL_INTERVAL = 12 * 3600  # 12 hours
_onboarding_status: dict[str, dict] = {}  # user_id -> {"status": ..., "error": ...}
_onboarding_lock = threading.Lock()
_UNKNOWN_GMAIL_WEBHOOK_TTL = 300  # 5 minutes
_unknown_gmail_webhook_emails: dict[str, float] = {}


def _is_auth0_mode() -> bool:
    """Return True when Auth0-backed login is explicitly enabled."""
    return (
        config.deployment_mode == "auth0"
        and bool(config.auth0_domain)
        and bool(config.auth0_client_id)
        and bool(config.auth0_client_secret)
    )


def _is_self_hosted_mode() -> bool:
    """Return True for local/self-hosted mode."""
    return config.deployment_mode == "self_hosted"


def _is_cached_unknown_gmail_webhook_email(email_address: str) -> bool:
    """Return True when an unknown webhook email was seen recently."""
    now = time.time()
    expires_at = _unknown_gmail_webhook_emails.get(email_address)
    if expires_at is None:
        return False
    if expires_at <= now:
        del _unknown_gmail_webhook_emails[email_address]
        return False
    return True


def _cache_unknown_gmail_webhook_email(email_address: str) -> None:
    """Avoid repeated DB lookups for unknown webhook emails."""
    _unknown_gmail_webhook_emails[email_address] = time.time() + _UNKNOWN_GMAIL_WEBHOOK_TTL


def _is_gmail_404(exc: Exception) -> bool:
    """Return True if exc is a Gmail API 404 (message deleted/not found)."""
    from googleapiclient.errors import HttpError

    return isinstance(exc, HttpError) and exc.resp.status == 404


async def _watch_renewal_loop():
    """Background loop: renew Gmail watches and clean up old processed messages."""
    await asyncio.sleep(60)  # let server finish starting
    while True:
        try:
            from scheduler.db import cleanup_processed_messages
            from scheduler.gmail.watch import renew_all_watches

            result = await asyncio.to_thread(renew_all_watches)
            logger.info("watch_renewal_loop: %s", result)
            deleted = await asyncio.to_thread(cleanup_processed_messages)
            if deleted:
                logger.info("watch_renewal_loop: cleaned up %d old processed_messages rows", deleted)
        except Exception:
            logger.exception("watch_renewal_loop: failed")
        await asyncio.sleep(_WATCH_RENEWAL_INTERVAL)


@asynccontextmanager
async def lifespan(app: FastAPI):
    task = asyncio.create_task(_watch_renewal_loop())
    yield
    task.cancel()


app = FastAPI(title="Scheduler Control Plane", lifespan=lifespan)

# Allow the web frontend to call the control plane (with and without www.)
_cors_origins = [config.web_app_url]
_url = config.web_app_url.rstrip("/")
if _url.startswith("https://www."):
    _cors_origins.append(_url.replace("https://www.", "https://", 1))
elif _url.startswith("http://www."):
    _cors_origins.append(_url.replace("http://www.", "http://", 1))
elif "://" in _url:
    scheme, rest = _url.split("://", 1)
    _cors_origins.append(f"{scheme}://www.{rest}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)


# --- Auth0 JWT validation ---

_jwks_client: PyJWKClient | None = None


def _get_jwks_client() -> PyJWKClient:
    global _jwks_client
    if _jwks_client is None:
        _jwks_client = PyJWKClient(f"https://{config.auth0_domain}/.well-known/jwks.json")
    return _jwks_client


def _validate_auth0_jwt(token: str) -> dict:
    signing_key = _get_jwks_client().get_signing_key_from_jwt(token)
    return jwt.decode(
        token, signing_key.key,
        algorithms=["RS256"],
        audience=config.auth0_audience,
        issuer=f"https://{config.auth0_domain}/",
    )


# --- Legacy HMAC session helpers (kept for transition period) ---


def _sign_session(user_id: str, email: str) -> str:
    """Create an HMAC-signed session token encoding user_id and email."""
    payload = json.dumps({"user_id": user_id, "email": email})
    sig = hmac.new(config.session_secret.encode(), payload.encode(), hashlib.sha256).hexdigest()
    return base64.urlsafe_b64encode(f"{payload}|{sig}".encode()).decode()


def _verify_session(token: str) -> dict | None:
    """Verify and decode an HMAC-signed session token."""
    try:
        decoded = base64.urlsafe_b64decode(token).decode()
        payload, sig = decoded.rsplit("|", 1)
        expected = hmac.new(config.session_secret.encode(), payload.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(sig, expected):
            return None
        return json.loads(payload)
    except Exception:
        return None


# --- Unified auth dependency ---


def get_authenticated_user(request: Request) -> dict:
    """Validate Auth0 JWT from Authorization header, with legacy HMAC fallback."""
    auth_header = request.headers.get("authorization", "")
    if not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Not authenticated")
    token = auth_header[7:]

    # Try Auth0 JWT first when Auth0 mode is enabled
    if _is_auth0_mode():
        try:
            payload = _validate_auth0_jwt(token)
            from scheduler.db import get_user_by_auth0_sub
            user = get_user_by_auth0_sub(payload["sub"])
            if not user:
                raise HTTPException(status_code=401, detail="User not found")
            return {"user_id": str(user.id), "email": user.email}
        except jwt.PyJWTError:
            pass  # Fall through to legacy HMAC

    # Legacy HMAC fallback (transition period)
    legacy = _verify_session(token)
    if legacy:
        return legacy

    raise HTTPException(status_code=401, detail="Invalid token")


# Alias for backward compatibility with internal callers
get_web_session = get_authenticated_user
get_web_user = get_authenticated_user


# --- Auth0 routes ---


@app.get("/auth/login")
def auth0_login(signup: str | None = None):
    """Start interactive login."""
    if _is_self_hosted_mode() and not _is_auth0_mode():
        redirect = f"/auth/google?signin=1" if signup == "1" else "/auth/google"
        return RedirectResponse(redirect)

    if not _is_auth0_mode():
        return RedirectResponse(f"{config.web_app_url}?error=auth0_not_enabled")

    params = {
        "client_id": config.auth0_client_id,
        "redirect_uri": f"{config.google_web_redirect_uri}/auth/callback",
        "response_type": "code",
        "scope": "openid profile email",
        "audience": config.auth0_audience,
    }
    if signup == "1":
        params["screen_hint"] = "signup"
    url = f"https://{config.auth0_domain}/authorize?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url)


def _is_onboarded(user_id: str, *, stash_calendar_id: str | None = None) -> bool:
    from scheduler.db import get_guides_for_user
    guides = get_guides_for_user(user_id)
    guide_names = {g.name for g in guides}
    has_guides = "scheduling_preferences" in guide_names and "email_style" in guide_names
    return has_guides and stash_calendar_id is not None


@app.get("/auth/callback")
def auth0_callback(code: str | None = None, error: str | None = None):
    """Handle Auth0 callback — exchange code for tokens, create/match user."""
    if not _is_auth0_mode():
        return RedirectResponse(f"{config.web_app_url}?error=auth0_not_enabled")

    if error:
        return RedirectResponse(f"{config.web_app_url}?error={error}")

    if not code:
        return RedirectResponse(f"{config.web_app_url}?error=missing_code")

    import httpx

    # Exchange authorization code for Auth0 tokens
    token_response = httpx.post(
        f"https://{config.auth0_domain}/oauth/token",
        json={
            "grant_type": "authorization_code",
            "client_id": config.auth0_client_id,
            "client_secret": config.auth0_client_secret,
            "code": code,
            "redirect_uri": f"{config.google_web_redirect_uri}/auth/callback",
        },
    )

    if token_response.status_code != 200:
        logger.error("Auth0 token exchange failed: %s", token_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=token_exchange_failed")

    tokens = token_response.json()
    access_token = tokens["access_token"]
    id_token = tokens.get("id_token", "")

    # Decode id_token to get email and sub (unverified is fine — we just got it from Auth0)
    id_claims = jwt.decode(id_token, options={"verify_signature": False})
    email = id_claims.get("email")
    auth0_sub = id_claims.get("sub")

    if not email or not auth0_sub:
        return RedirectResponse(f"{config.web_app_url}?error=missing_user_info")

    from scheduler.db import (
        create_user_from_auth0,
        get_user_by_auth0_sub,
        get_user_by_email,
        set_auth0_sub,
    )

    # Look up user by auth0_sub first, then by email for migration
    user = get_user_by_auth0_sub(auth0_sub)
    if not user:
        user = get_user_by_email(email)
        if user:
            # Existing user logging in via Auth0 for the first time — link accounts
            set_auth0_sub(str(user.id), auth0_sub)
            logger.info("auth0_callback: linked existing user=%s to auth0_sub=%s", user.id, auth0_sub)
        else:
            # Brand new user
            user = create_user_from_auth0(email, auth0_sub)
            logger.info("auth0_callback: created new user=%s for auth0_sub=%s", user.id, auth0_sub)

    from starlette.background import BackgroundTask

    # Check if user has Google tokens and onboarding status
    has_google = user.google_refresh_token is not None
    is_onboarded = has_google and _is_onboarded(str(user.id), stash_calendar_id=user.stash_calendar_id)

    if has_google and is_onboarded:
        logger.info("auth0_callback: returning user=%s, renewing gmail watch", user.id)
        background = BackgroundTask(_renew_gmail_watch, str(user.id))
        redirect_url = f"{config.web_app_url}/settings?token={access_token}"
    elif has_google and not is_onboarded:
        logger.info("auth0_callback: user=%s has google but not onboarded, starting onboarding", user.id)
        with _onboarding_lock:
            if _onboarding_status.get(str(user.id), {}).get("status") == "running":
                logger.info("auth0_callback: onboarding already running for user=%s", user.id)
                background = None
            else:
                background = BackgroundTask(_run_onboarding_for_runtime, str(user.id))
        redirect_url = f"{config.web_app_url}/onboarding?token={access_token}"
    else:
        logger.info("auth0_callback: user=%s needs google connect", user.id)
        background = None
        redirect_url = f"{config.web_app_url}/onboarding?token={access_token}&needs_google=1"

    return RedirectResponse(redirect_url, background=background)


@app.get("/auth/logout")
def auth0_logout():
    """Redirect to Auth0 logout endpoint."""
    if not _is_auth0_mode():
        return RedirectResponse(config.web_app_url)

    params = {
        "client_id": config.auth0_client_id,
        "returnTo": config.web_app_url,
    }
    url = f"https://{config.auth0_domain}/v2/logout?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url)


# --- Google Connect flow (separate from login) ---

# Temporary store for Google connect OAuth state tokens
_google_connect_states: dict[str, float] = {}


@app.get("/auth/google/connect")
def auth_google_connect(token: str | None = None):
    """Start Google API token OAuth flow. Requires authenticated session token via query param."""
    if not token:
        raise HTTPException(status_code=401, detail="Missing token")

    # Validate Auth0 JWT (or legacy HMAC)
    try:
        if _is_auth0_mode():
            payload = _validate_auth0_jwt(token)
            from scheduler.db import get_user_by_auth0_sub
            user = get_user_by_auth0_sub(payload["sub"])
            if not user:
                raise HTTPException(status_code=401, detail="User not found")
            user_id = str(user.id)
        else:
            legacy = _verify_session(token)
            if not legacy:
                raise HTTPException(status_code=401, detail="Invalid token")
            user_id = legacy["user_id"]
    except jwt.PyJWTError:
        raise HTTPException(status_code=401, detail="Invalid token")

    state_data = f"{secrets.token_urlsafe(32)}|user_id={user_id}|auth_token={token}"
    _google_connect_states[state_data] = time.time()

    params = {
        "client_id": config.google_client_id,
        "redirect_uri": f"{config.google_web_redirect_uri}/auth/google/callback",
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "consent",
        "state": state_data,
    }
    url = f"https://accounts.google.com/o/oauth2/v2/auth?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url)


@app.get("/auth/google/callback")
def auth_google_connect_callback(
    code: str | None = None, state: str | None = None, error: str | None = None
):
    """Handle Google OAuth callback for the Connect flow."""
    if error:
        return RedirectResponse(f"{config.web_app_url}?error={error}")

    if not code or not state:
        return RedirectResponse(f"{config.web_app_url}?error=missing_params")

    # Validate state
    issued_at = _google_connect_states.pop(state, None)
    if not issued_at or (time.time() - issued_at > 600):
        return RedirectResponse(f"{config.web_app_url}?error=invalid_state")

    # Extract user_id and auth_token from state
    parts = state.split("|")
    state_dict = {}
    for part in parts[1:]:
        if "=" in part:
            k, v = part.split("=", 1)
            state_dict[k] = v
    user_id = state_dict.get("user_id")
    auth_token = state_dict.get("auth_token")

    if not user_id:
        return RedirectResponse(f"{config.web_app_url}?error=invalid_state")

    import httpx

    # Exchange authorization code for Google tokens
    token_response = httpx.post(
        "https://oauth2.googleapis.com/token",
        data={
            "code": code,
            "client_id": config.google_client_id,
            "client_secret": config.google_client_secret,
            "redirect_uri": f"{config.google_web_redirect_uri}/auth/google/callback",
            "grant_type": "authorization_code",
        },
    )

    if token_response.status_code != 200:
        logger.error("Google token exchange failed: %s", token_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=token_exchange_failed")

    tokens = token_response.json()
    google_access_token = tokens["access_token"]
    google_refresh_token = tokens.get("refresh_token")

    if not google_refresh_token:
        return RedirectResponse(f"{config.web_app_url}?error=no_refresh_token")

    from scheduler.db import update_google_tokens

    expires_in = tokens.get("expires_in")
    expires_at = None
    if expires_in:
        from datetime import timedelta
        expires_at = datetime.now() + timedelta(seconds=expires_in)

    update_google_tokens(
        user_id=user_id,
        google_refresh_token=google_refresh_token,
        google_access_token=google_access_token,
        access_token_expires_at=expires_at,
    )

    # Check onboarding status
    from scheduler.db import get_user_by_id as _get_user
    db_user = _get_user(user_id)
    is_onboarded = _is_onboarded(user_id, stash_calendar_id=db_user.stash_calendar_id if db_user else None)

    from starlette.background import BackgroundTask

    token_param = f"token={auth_token}" if auth_token else ""

    if is_onboarded:
        logger.info("google_connect: returning user=%s, renewing gmail watch", user_id)
        background = BackgroundTask(_renew_gmail_watch, user_id)
        redirect_url = f"{config.web_app_url}/settings?{token_param}"
    else:
        logger.info("google_connect: starting onboarding for user=%s", user_id)
        with _onboarding_lock:
            if _onboarding_status.get(user_id, {}).get("status") == "running":
                logger.info("google_connect: onboarding already running for user=%s", user_id)
                background = None
            else:
                background = BackgroundTask(_run_onboarding_for_runtime, user_id)
        redirect_url = f"{config.web_app_url}/onboarding?{token_param}"

    return RedirectResponse(redirect_url, background=background)


# --- Legacy Google OAuth routes (kept for transition period) ---

# Temporary store for OAuth state tokens (state -> timestamp)
_oauth_states: dict[str, float] = {}


@app.get("/auth/google")
def auth_google_redirect(signin: str | None = None):
    """Redirect the user to Google's OAuth consent screen.

    If signin=1, uses prompt=select_account (returning users just pick their account).
    Otherwise, uses prompt=consent (new users grant full permissions).
    """
    is_signin = signin == "1"
    state_data = f"{secrets.token_urlsafe(32)}|signin={1 if is_signin else 0}"
    _oauth_states[state_data] = time.time()

    params = {
        "client_id": config.google_client_id,
        "redirect_uri": config.google_web_redirect_uri,
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "select_account" if is_signin else "consent",
        "state": state_data,
    }
    url = f"https://accounts.google.com/o/oauth2/v2/auth?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url)


@app.get("/")
def root_callback(code: str | None = None, state: str | None = None, error: str | None = None):
    """Handle the OAuth callback at the root path (Google redirects to http://localhost:8080).

    If no OAuth query params are present, returns a simple health check.
    """
    if not code and not state and not error:
        return {"status": "ok", "service": "scheduler-control-plane"}
    return auth_google_callback(code=code, state=state, error=error)


def auth_google_callback(code: str | None = None, state: str | None = None, error: str | None = None):
    """Handle the OAuth callback from Google (legacy flow).

    Exchanges the authorization code for tokens, upserts the user in the
    database, and redirects to the web app with a signed session cookie.
    """
    if error:
        return RedirectResponse(f"{config.web_app_url}?error={error}")

    if not code or not state:
        return RedirectResponse(f"{config.web_app_url}?error=missing_params")

    # Validate state
    issued_at = _oauth_states.pop(state, None)
    if not issued_at or (time.time() - issued_at > 600):
        return RedirectResponse(f"{config.web_app_url}?error=invalid_state")

    is_signin = state.endswith("|signin=1")

    # Exchange authorization code for tokens
    import httpx

    token_response = httpx.post(
        "https://oauth2.googleapis.com/token",
        data={
            "code": code,
            "client_id": config.google_client_id,
            "client_secret": config.google_client_secret,
            "redirect_uri": config.google_web_redirect_uri,
            "grant_type": "authorization_code",
        },
    )

    if token_response.status_code != 200:
        logger.error("OAuth token exchange failed: %s", token_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=token_exchange_failed")

    tokens = token_response.json()
    access_token = tokens["access_token"]
    refresh_token = tokens.get("refresh_token")

    # Get user's email from Google
    userinfo_response = httpx.get(
        "https://www.googleapis.com/oauth2/v2/userinfo",
        headers={"Authorization": f"Bearer {access_token}"},
    )

    if userinfo_response.status_code != 200:
        logger.error("Userinfo request failed: status=%s body=%s", userinfo_response.status_code, userinfo_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=userinfo_failed")

    email = userinfo_response.json().get("email")
    if not email:
        return RedirectResponse(f"{config.web_app_url}?error=no_email")

    from scheduler.db import get_user_by_email, upsert_user

    if refresh_token:
        # Sign-up flow (or sign-in that happened to return a refresh token)
        expires_in = tokens.get("expires_in")
        expires_at = None
        if expires_in:
            from datetime import timedelta
            expires_at = datetime.now() + timedelta(seconds=expires_in)

        user = upsert_user(
            email=email,
            google_refresh_token=refresh_token,
            google_access_token=access_token,
            access_token_expires_at=expires_at,
        )
    else:
        # Sign-in flow: no refresh token, look up existing user
        user = get_user_by_email(email)
        if not user:
            logger.warning("sign-in attempt for unknown user: %s", email)
            return RedirectResponse(f"{config.web_app_url}?error=account_not_found")

    # Determine if user is already onboarded
    is_onboarded = _is_onboarded(str(user.id), stash_calendar_id=user.stash_calendar_id)

    from starlette.background import BackgroundTask

    if is_onboarded:
        # Returning user: just renew Gmail watch, redirect to settings
        logger.info("sign-in: returning user=%s, renewing gmail watch", user.id)
        background = BackgroundTask(_renew_gmail_watch, str(user.id))
        redirect_url = f"{config.web_app_url}/settings"
    else:
        # New user: run full onboarding, redirect to onboarding
        logger.info("onboarding: starting all agents for user=%s after OAuth", user.id)
        with _onboarding_lock:
            if _onboarding_status.get(str(user.id), {}).get("status") == "running":
                logger.info("onboarding: already running for user=%s", user.id)
                background = None
            else:
                background = BackgroundTask(_run_onboarding_for_runtime, str(user.id))
        redirect_url = f"{config.web_app_url}/onboarding"

    # Create signed session and redirect to web app
    session_token = _sign_session(str(user.id), email)
    separator = "&" if "?" in redirect_url else "?"
    redirect_url_with_token = f"{redirect_url}{separator}session={session_token}"
    return RedirectResponse(redirect_url_with_token, background=background)


@app.get("/auth/me")
def auth_me(session: dict = Depends(get_authenticated_user)):
    """Return the current user's info."""
    return {"user_id": session["user_id"], "email": session["email"]}


# --- Session store ---

sessions: dict[str, dict] = {}

_SESSION_TTL = 600  # 10 minutes — e2b sandboxes default to 5 min max


def register_session(session_token: str, user_id: str) -> None:
    """Register a session with Google credentials for a user.

    Loads credentials from the database if DATABASE_URL is set and the user
    exists. Falls back to local OAuth flow (token.json) for development.
    """
    _cleanup_expired_sessions()

    from scheduler.db import get_user_by_id

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)

    db_user = get_user_by_id(user_id)
    extra_ids = (db_user.calendar_ids or []) if db_user else []
    calendar = CalendarClient(creds, config.stash_calendar_name, extra_calendar_ids=extra_ids)
    calendar.get_or_create_stash_calendar()

    sessions[session_token] = {
        "user_id": user_id,
        "gmail": gmail,
        "calendar": calendar,
        "created_at": time.time(),
    }


def _cleanup_expired_sessions() -> None:
    """Remove sessions older than _SESSION_TTL."""
    now = time.time()
    expired = [tok for tok, s in sessions.items() if now - s["created_at"] > _SESSION_TTL]
    for tok in expired:
        del sessions[tok]


def get_session(authorization: str = Header()) -> dict:
    """Validate the session token from the Authorization header."""
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid authorization header")

    token = authorization.removeprefix("Bearer ")
    session = sessions.get(token)
    if not session:
        raise HTTPException(status_code=401, detail="Invalid or expired session token")

    if time.time() - session["created_at"] > _SESSION_TTL:
        del sessions[token]
        raise HTTPException(status_code=401, detail="Invalid or expired session token")

    return session


# --- Serialization helpers ---


def _serialize_email(email) -> dict:
    return {
        "id": email.id,
        "thread_id": email.thread_id,
        "sender": email.sender,
        "recipient": email.recipient,
        "cc": email.cc,
        "subject": email.subject,
        "body": email.body,
        "date": email.date.isoformat(),
        "snippet": email.snippet,
    }


def _serialize_event(event) -> dict:
    return {
        "id": event.id,
        "summary": event.summary,
        "start": event.start.isoformat(),
        "end": event.end.isoformat(),
        "description": event.description,
    }


# --- Request models ---


class SearchEmailsRequest(BaseModel):
    query: str
    max_results: int = 50


class CreateDraftRequest(BaseModel):
    thread_id: str
    to: str
    cc: str = ""
    subject: str
    body: str
    send_invite: bool = False
    invite_attendee_email: str | None = None
    invite_event_summary: str | None = None
    invite_event_start: str | None = None
    invite_event_end: str | None = None
    invite_add_google_meet: bool = False


class SendEmailRequest(BaseModel):
    thread_id: str
    to: str
    cc: str = ""
    subject: str
    body: str


class GetEventsRequest(BaseModel):
    start_date: str
    end_date: str
    include_primary: bool = True


class FindEventRequest(BaseModel):
    summary: str
    start_date: str
    end_date: str


class AddEventRequest(BaseModel):
    summary: str
    start: str
    end: str
    description: str = ""


class UpdateBrandingRequest(BaseModel):
    enabled: bool


class UpdateAutopilotRequest(BaseModel):
    enabled: bool


class UpdateSystemEnabledRequest(BaseModel):
    enabled: bool


class WriteGuideRequest(BaseModel):
    name: str
    content: str


# --- Gmail routes ---


@app.post("/api/v1/gmail/search")
def gmail_search(req: SearchEmailsRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    emails = gmail.search(query=req.query, max_results=req.max_results)
    return {"emails": [_serialize_email(e) for e in emails]}


@app.get("/api/v1/gmail/thread/{thread_id}")
def gmail_thread(thread_id: str, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    messages = gmail.get_thread(thread_id)
    return {"messages": [_serialize_email(e) for e in messages]}


@app.get("/api/v1/gmail/message/{message_id}")
def gmail_message(message_id: str, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    email = gmail.get_email(message_id)
    return {"email": _serialize_email(email)}


@app.post("/api/v1/gmail/draft")
def gmail_draft(req: CreateDraftRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    from scheduler.db import create_pending_invite, get_user_by_id

    user = get_user_by_id(session["user_id"])
    body = req.body
    content_type = "plain"
    if user and user.stash_branding_enabled:
        html_body = html.escape(body).replace("\n", "<br>")
        html_body += '<br><br>sent by <a href="https://tryscheduled.com">Scheduled.</a>'
        body = html_body
        content_type = "html"

    draft_id = gmail.create_draft(
        thread_id=req.thread_id, to=req.to, subject=req.subject, body=body, content_type=content_type, cc=req.cc
    )

    if req.send_invite:
        if not all([
            req.invite_attendee_email,
            req.invite_event_summary,
            req.invite_event_start,
            req.invite_event_end,
        ]):
            raise HTTPException(status_code=400, detail="Missing invite fields")

        create_pending_invite(
            user_id=session["user_id"],
            thread_id=req.thread_id,
            attendee_email=req.invite_attendee_email,
            event_summary=req.invite_event_summary,
            event_start=datetime.fromisoformat(req.invite_event_start),
            event_end=datetime.fromisoformat(req.invite_event_end),
            add_google_meet=req.invite_add_google_meet,
        )

    return {"draft_id": draft_id}


@app.post("/api/v1/gmail/send")
def gmail_send(req: SendEmailRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    body = req.body
    content_type = "plain"
    if user and user.stash_branding_enabled:
        html_body = html.escape(body).replace("\n", "<br>")
        html_body += '<br><br>sent by <a href="https://tryscheduled.com">Scheduled.</a>'
        body = html_body
        content_type = "html"

    message_id = gmail.send_email(
        thread_id=req.thread_id,
        to=req.to,
        subject=req.subject,
        body=body,
        content_type=content_type,
        cc=req.cc,
    )
    return {"message_id": message_id, "status": "sent"}


# --- Calendar routes ---


@app.post("/api/v1/calendar/events")
def calendar_events(req: GetEventsRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    events = calendar.get_all_events(
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
        include_primary=req.include_primary,
    )
    return {"events": [_serialize_event(e) for e in events]}


@app.post("/api/v1/calendar/find")
def calendar_find(req: FindEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = calendar.find_event(
        summary=req.summary,
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
    )
    if event:
        return {"exists": True, "event": _serialize_event(event)}
    return {"exists": False, "event": None}


@app.get("/api/v1/calendar/timezone")
def calendar_timezone(session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    return {"timezone": calendar.get_user_timezone()}


@app.post("/api/v1/calendar/add")
def calendar_add(req: AddEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = Event(
        id=None,
        summary=req.summary,
        start=datetime.fromisoformat(req.start),
        end=datetime.fromisoformat(req.end),
        description=req.description,
        source="gmail",
    )
    event_id = calendar.add_event(event)
    return {"event_id": event_id, "status": "created"}


# --- Settings routes ---


@app.get("/api/v1/settings/branding")
def settings_branding_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"stash_branding_enabled": user.stash_branding_enabled}


@app.put("/api/v1/settings/branding")
def settings_branding_put(req: UpdateBrandingRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_stash_branding

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_stash_branding(session["user_id"], req.enabled)
    return {"stash_branding_enabled": req.enabled}


@app.get("/api/v1/settings/autopilot")
def settings_autopilot_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"autopilot_enabled": user.autopilot_enabled}


@app.put("/api/v1/settings/autopilot")
def settings_autopilot_put(req: UpdateAutopilotRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_autopilot

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_autopilot(session["user_id"], req.enabled)
    return {"autopilot_enabled": req.enabled}


class UpdateSalesEmailRequest(BaseModel):
    enabled: bool


@app.get("/api/v1/settings/sales-emails")
def settings_sales_emails_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"process_sales_emails": user.process_sales_emails}


@app.put("/api/v1/settings/sales-emails")
def settings_sales_emails_put(req: UpdateSalesEmailRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_process_sales_emails

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_process_sales_emails(session["user_id"], req.enabled)
    return {"process_sales_emails": req.enabled}


@app.get("/api/v1/settings/system")
def settings_system_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"system_enabled": user.system_enabled}


@app.put("/api/v1/settings/system")
def settings_system_put(req: UpdateSystemEnabledRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_system_enabled

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_system_enabled(session["user_id"], req.enabled)
    return {"system_enabled": req.enabled}


# --- Guide routes ---


class ReadGuideRequest(BaseModel):
    name: str


@app.post("/api/v1/guides/write")
def guides_write(req: WriteGuideRequest, session: dict = Depends(get_session)):
    from scheduler.guides import save_guide

    user_id = session["user_id"]
    save_guide(name=req.name, content=req.content, user_id=user_id)
    return {"status": "written"}


@app.post("/api/v1/guides/read")
def guides_read(req: ReadGuideRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_guide

    user_id = session["user_id"]
    guide = get_guide(user_id=user_id, name=req.name)
    if not guide:
        raise HTTPException(status_code=404, detail=f"Guide '{req.name}' not found")
    return {"name": guide.name, "content": guide.content, "updated_at": guide.updated_at.isoformat()}


# --- Onboarding ---


def _renew_gmail_watch(user_id: str) -> None:
    """Background task: renew Gmail watch for a returning user."""
    from scheduler.gmail.watch import setup_gmail_watch

    try:
        setup_gmail_watch(user_id)
        logger.info("sign-in: gmail watch renewed for user=%s", user_id)
    except Exception:
        logger.exception("sign-in: failed to renew gmail watch for user=%s", user_id)


def _run_onboarding_all(user_id: str) -> None:
    """Background task: run backfill + both guide-writer agents for a user, then set up Gmail watch."""
    import anyio
    from scheduler.gmail.watch import setup_gmail_watch
    from scheduler.guides.backends import LocalGuideBackend
    from scheduler.guides.preferences import run_preferences_agent
    from scheduler.guides.style import run_style_agent
    from scheduler.onboarding.agent import _run_backfill_async as _run_backfill
    from scheduler.onboarding.backends import LocalBackend

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    cal_id = calendar.get_or_create_stash_calendar()
    if cal_id:
        from scheduler.db import update_stash_calendar_id
        update_stash_calendar_id(user_id, cal_id)

    guide_backend = LocalGuideBackend(gmail, calendar, user_id=user_id)
    onboarding_backend = LocalBackend(gmail, calendar)

    async def _run():
        async with anyio.create_task_group() as tg:
            tg.start_soon(_run_backfill, onboarding_backend, config.onboarding_lookback_days)
            tg.start_soon(run_preferences_agent, guide_backend)
            tg.start_soon(run_style_agent, guide_backend)

    anyio.run(_run)

    # Send lifecycle welcome email (non-blocking — failure never stops onboarding)
    try:
        from scheduler.lifecycle.welcome import send_lifecycle_email

        send_lifecycle_email(user_id)
    except Exception:
        logger.exception("onboarding: lifecycle email failed for user=%s", user_id)

    # Set up Gmail watch so incoming emails are processed
    try:
        setup_gmail_watch(user_id)
        logger.info("onboarding: gmail watch set up for user=%s", user_id)
    except Exception:
        logger.exception("onboarding: failed to set up gmail watch for user=%s", user_id)


def _run_onboarding_for_runtime(user_id: str) -> None:
    """Dispatch onboarding to the configured runtime."""
    from scheduler.db import update_system_enabled

    with _onboarding_lock:
        if _onboarding_status.get(user_id, {}).get("status") == "running":
            logger.info("onboarding: already running for user=%s, skipping", user_id)
            return
        _onboarding_status[user_id] = {
            "status": "running",
            "agents": {
                "backfill": "running",
                "preferences": "running",
                "style": "running",
            },
        }
    try:
        runtime = config.agent_runtime.strip().lower()
        if runtime == "local":
            _run_onboarding_all(user_id)
            update_system_enabled(user_id, True)
            logger.info("onboarding: system enabled for user=%s", user_id)
            with _onboarding_lock:
                _onboarding_status.pop(user_id, None)
            return

        if runtime == "e2b":
            control_plane_url = config.control_plane_public_url.strip()
            if not control_plane_url:
                raise RuntimeError("CONTROL_PLANE_PUBLIC_URL must be set when AGENT_RUNTIME=e2b")

            # Ensure Stash calendar exists before sandbox launch (agents need it)
            creds = load_credentials(user_id)
            calendar = CalendarClient(creds, config.stash_calendar_name)
            cal_id = calendar.get_or_create_stash_calendar()
            if cal_id:
                from scheduler.db import update_stash_calendar_id
                update_stash_calendar_id(user_id, cal_id)

            def _on_agent_done(agent_name: str, success: bool) -> None:
                with _onboarding_lock:
                    entry = _onboarding_status.get(user_id)
                    if entry and "agents" in entry:
                        entry["agents"][agent_name] = "done" if success else "failed"

            from scheduler.run_e2b import launch_onboarding_in_sandbox

            launch_onboarding_in_sandbox(
                user_id=user_id,
                control_plane_url=control_plane_url,
                lookback_days=config.onboarding_lookback_days,
                on_agent_done=_on_agent_done,
            )

            # Send lifecycle welcome email (runs on control plane, not in sandbox)
            try:
                from scheduler.lifecycle.welcome import send_lifecycle_email

                send_lifecycle_email(user_id)
            except Exception:
                logger.exception("onboarding[e2b]: lifecycle email failed for user=%s", user_id)

            # Set up Gmail watch so incoming emails are processed
            from scheduler.gmail.watch import setup_gmail_watch

            try:
                setup_gmail_watch(user_id)
                logger.info("onboarding[e2b]: gmail watch set up for user=%s", user_id)
            except Exception:
                logger.exception("onboarding[e2b]: failed to set up gmail watch for user=%s", user_id)

            update_system_enabled(user_id, True)
            logger.info("onboarding[e2b]: system enabled for user=%s", user_id)

            with _onboarding_lock:
                _onboarding_status.pop(user_id, None)
            return

        raise RuntimeError(f"Unsupported AGENT_RUNTIME: {config.agent_runtime}")
    except Exception as e:
        logger.exception("onboarding: failed for user=%s", user_id)
        with _onboarding_lock:
            _onboarding_status[user_id] = {"status": "failed", "error": str(e)}


def _compose_draft_for_runtime(
    user_id: str,
    email,
    classification,
    gmail: GmailClient,
    calendar: CalendarClient,
    autopilot: bool,
    user_email: str = "",
) -> str | None:
    runtime = config.agent_runtime.strip().lower()

    if runtime == "local":
        from scheduler.drafts.composer import DraftComposer, LocalDraftBackend

        backend = LocalDraftBackend(gmail, calendar, user_id=user_id)
        composer = DraftComposer(backend, user_id, autopilot=autopilot, user_email=user_email)
        return composer.compose_and_create_draft(email, classification)

    if runtime == "e2b":
        control_plane_url = config.control_plane_public_url.strip()
        if not control_plane_url:
            raise RuntimeError("CONTROL_PLANE_PUBLIC_URL must be set when AGENT_RUNTIME=e2b")

        from scheduler.run_e2b import launch_draft_composer_in_sandbox

        return launch_draft_composer_in_sandbox(
            user_id=user_id,
            control_plane_url=control_plane_url,
            email_payload=_serialize_email(email),
            classification_payload={
                "intent": classification.intent.value,
                "confidence": classification.confidence,
                "summary": classification.summary,
                "proposed_times": classification.proposed_times,
                "participants": classification.participants,
                "duration_minutes": classification.duration_minutes,
            },
            autopilot=autopilot,
            user_email=user_email,
        )

    raise RuntimeError(f"Unsupported AGENT_RUNTIME: {config.agent_runtime}")


@app.post("/api/v1/onboarding/run")
def onboarding_run(request: Request, background_tasks: BackgroundTasks):
    """Kick off the style + preferences guide agents for this user."""
    session = get_web_session(request)
    user_id = session["user_id"]
    with _onboarding_lock:
        if _onboarding_status.get(user_id, {}).get("status") == "running":
            logger.info("onboarding: already running for user=%s", user_id)
            return {"status": "already_running"}
    logger.info("onboarding: starting all agents for user=%s", user_id)
    background_tasks.add_task(_run_onboarding_for_runtime, user_id)
    return {"status": "started"}


# --- Gmail webhook ---



def _process_new_messages(user_id: str, email_address: str, history_id: str) -> None:
    """Background task: fetch new messages since last history ID and log them.

    This is the hook point where the classifier agent will be triggered.
    """
    from scheduler.db import get_user_by_id, update_gmail_history_id

    user = get_user_by_id(user_id)
    if not user:
        return
    if not user.system_enabled:
        logger.info("gmail_webhook: system disabled for user=%s, skipping", email_address)
        return
    if not user.gmail_history_id:
        # First notification — just store the history ID baseline
        update_gmail_history_id(user_id, history_id)
        logger.info("gmail_webhook: stored initial history_id=%s for user=%s", history_id, email_address)
        return

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)

    try:
        new_message_ids = gmail.get_history(user.gmail_history_id)
    except Exception:
        # History ID may be too old (> 7 days). Reset baseline.
        logger.warning("gmail_webhook: history expired for user=%s, resetting", email_address)
        update_gmail_history_id(user_id, history_id)
        return

    update_gmail_history_id(user_id, history_id)

    if not new_message_ids:
        return

    logger.info(
        "gmail_webhook: %d new message(s) for user=%s: %s",
        len(new_message_ids),
        email_address,
        new_message_ids,
    )

    from scheduler.classifier.intent import SchedulingIntent, classify_email
    from scheduler.classifier.newsletter import is_mass_email
    from scheduler.db import try_claim_message

    calendar = CalendarClient(creds, config.stash_calendar_name, extra_calendar_ids=user.calendar_ids or [])

    for message_id in new_message_ids:
        # Atomic claim: prevents duplicate processing from concurrent webhooks
        if not try_claim_message(user_id, message_id):
            logger.info("gmail_webhook: message %s already claimed, skipping", message_id)
            continue

        try:
            email = gmail.get_email(message_id)

            # For messages sent by the user: check if this is a sent invite draft
            if email.sender and email_address in email.sender:
                from scheduler.db import delete_pending_invite, get_pending_invite_by_thread

                invite = get_pending_invite_by_thread(user_id, email.thread_id)
                if not invite:
                    logger.info("gmail_webhook: message %s is from the user, skipping", message_id)
                    continue

                invite_age_hours = (datetime.now(timezone.utc) - invite.created_at.replace(tzinfo=timezone.utc)).total_seconds() / 3600

                # Skip stale invites (>24h old) — user likely forgot about them
                if invite_age_hours > 24:
                    logger.info(
                        "gmail_webhook: pending invite for thread %s is %.1fh old, expired — deleting",
                        email.thread_id,
                        invite_age_hours,
                    )
                    delete_pending_invite(str(invite.id))
                    continue

                # Classify whether the sent message still confirms the meeting
                from scheduler.classifier.intent import classify_sent_message_confirms_invite

                confirms = classify_sent_message_confirms_invite(email.body, invite.event_summary)
                if not confirms:
                    logger.info(
                        "gmail_webhook: message %s in thread %s does not confirm the meeting, deleting pending invite",
                        message_id,
                        email.thread_id,
                    )
                    delete_pending_invite(str(invite.id))
                    continue

                logger.info(
                    "gmail_webhook: message %s confirms invite for thread %s, creating calendar event",
                    message_id,
                    email.thread_id,
                )
                try:
                    event_id = calendar.create_invite_event(
                        summary=invite.event_summary,
                        start=invite.event_start,
                        end=invite.event_end,
                        attendee_email=invite.attendee_email,
                        add_google_meet=invite.add_google_meet,
                    )
                    delete_pending_invite(str(invite.id))
                    logger.info("gmail_webhook: created invite event %s for thread %s", event_id, email.thread_id)
                except Exception:
                    logger.exception("gmail_webhook: failed to create invite event for thread %s", email.thread_id)
                continue

            # Skip emails from Scheduled's own sending addresses (e.g. reasoning emails)
            sender_str = email.sender or ""
            if (config.postmark_from_email and config.postmark_from_email in sender_str) or \
               (config.postmark_bot_email and config.postmark_bot_email in sender_str):
                logger.info("gmail_webhook: message %s is from Scheduled, skipping", message_id)
                continue

            # Skip newsletters / mass emails (before classifier, saves API cost)
            if is_mass_email(email.headers, email.sender):
                logger.info("gmail_webhook: message %s is a mass email/newsletter, skipping", message_id)
                continue

            # Fetch full thread for classifier context
            thread_messages = []
            try:
                thread_emails = gmail.get_thread(email.thread_id)
                for t_email in thread_emails:
                    if t_email.id == email.id:
                        break
                    thread_messages.append({
                        "sender": t_email.sender,
                        "body": t_email.body,
                        "date": t_email.date.isoformat(),
                    })
            except Exception:
                logger.warning("gmail_webhook: failed to fetch thread %s for context, classifying without", email.thread_id)

            classification = classify_email(
                email.subject, email.body, email.sender,
                thread_messages=thread_messages,
                recipient=email.recipient, cc=email.cc,
            )

            if classification.intent == SchedulingIntent.NOT_SCHEDULING:
                logger.info("gmail_webhook: message %s is not scheduling-related, skipping", message_id)
                continue

            # Skip cold outreach unless user opted in
            if classification.is_sales_email and not user.process_sales_emails:
                logger.info("gmail_webhook: message %s is cold outreach, skipping", message_id)
                continue

            logger.info(
                "gmail_webhook: message %s classified as %s (confidence=%.2f), composing draft",
                message_id,
                classification.intent.value,
                classification.confidence,
            )

            draft_id = _compose_draft_for_runtime(
                user_id=user_id,
                email=email,
                classification=classification,
                gmail=gmail,
                calendar=calendar,
                autopilot=user.autopilot_enabled,
                user_email=email_address,
            )
            if draft_id is None:
                logger.info("gmail_webhook: thread for message %s already resolved, no draft created", message_id)
            else:
                logger.info("gmail_webhook: created draft %s for message %s", draft_id, message_id)
                if user.reasoning_emails_enabled:
                    try:
                        from scheduler.lifecycle.reasoning import send_reasoning_email
                        send_reasoning_email(
                            user_email=email_address,
                            thread_id=email.thread_id,
                            subject=email.subject,
                            classification=classification,
                            gmail=gmail,
                            calendar=calendar,
                        )
                    except Exception:
                        logger.exception("gmail_webhook: failed to send reasoning email for message %s", message_id)

        except Exception as exc:
            # If Gmail returns 404, the message was deleted/moved — don't retry
            if _is_gmail_404(exc):
                logger.warning("gmail_webhook: message %s not found (deleted?), skipping", message_id)
            else:
                logger.exception("gmail_webhook: failed to process message %s for user=%s", message_id, email_address)


@app.post("/webhooks/gmail")
async def gmail_webhook(request: Request, background_tasks: BackgroundTasks):
    """Receive Gmail push notifications via Google Cloud Pub/Sub.

    Google sends a POST with a Pub/Sub message whose data is a base64-encoded
    JSON object containing the user's email address and the latest historyId.

    Verified via a shared secret token passed as a query parameter. The Pub/Sub
    push subscription URL should be configured as:
        https://<host>/webhooks/gmail?token=<GMAIL_WEBHOOK_TOKEN>
    """
    if config.gmail_webhook_token:
        token = request.query_params.get("token", "")
        if not hmac.compare_digest(token, config.gmail_webhook_token):
            raise HTTPException(status_code=403, detail="Invalid webhook token")

    from scheduler.db import get_user_by_email

    body = await request.json()
    message = body.get("message", {})
    data_b64 = message.get("data", "")

    if not data_b64:
        raise HTTPException(status_code=400, detail="Missing message data")

    try:
        payload = json.loads(base64.urlsafe_b64decode(data_b64))
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid message data")

    email_address = payload.get("emailAddress")
    history_id = str(payload.get("historyId", ""))

    if not email_address or not history_id:
        raise HTTPException(status_code=400, detail="Missing emailAddress or historyId")

    if _is_cached_unknown_gmail_webhook_email(email_address):
        logger.info("gmail_webhook: cached unknown email %s", email_address)
        return {"status": "ignored", "reason": "unknown user"}

    user = await asyncio.to_thread(get_user_by_email, email_address)
    if not user:
        _cache_unknown_gmail_webhook_email(email_address)
        logger.warning("gmail_webhook: unknown email %s", email_address)
        # Return 200 so Pub/Sub doesn't retry for unknown users
        return {"status": "ignored", "reason": "unknown user"}

    background_tasks.add_task(_process_new_messages, str(user.id), email_address, history_id)

    return {"status": "ok"}


# --- Web API routes ---


@app.get("/web/api/v1/onboarding/status")
def web_onboarding_status(user: dict = Depends(get_authenticated_user)):
    from scheduler.db import get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    connected = db_user is not None and db_user.google_refresh_token is not None

    if connected:
        ready = _is_onboarded(user["user_id"], stash_calendar_id=db_user.stash_calendar_id if db_user else None)
    else:
        ready = False

    result = {"ready": ready, "connected": connected}
    if not ready:
        status_entry = _onboarding_status.get(user["user_id"])
        if status_entry:
            if status_entry.get("status") == "failed":
                result["failed"] = True
                result["error"] = status_entry.get("error", "Unknown error")
            if "agents" in status_entry:
                result["agents"] = status_entry["agents"]
    return result


@app.get("/web/api/v1/settings")
def web_settings_get(user: dict = Depends(get_authenticated_user)):
    from scheduler.db import get_guides_for_user, get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")

    guides = get_guides_for_user(user["user_id"])

    return {
        "system_enabled": db_user.system_enabled,
        "autopilot_enabled": db_user.autopilot_enabled,
        "process_sales_emails": db_user.process_sales_emails,
        "stash_branding_enabled": db_user.stash_branding_enabled,
        "reasoning_emails_enabled": db_user.reasoning_emails_enabled,
        "stash_calendar_id": db_user.stash_calendar_id,
        "calendar_ids": db_user.calendar_ids or [],
        "guides": [
            {"name": g.name, "content": g.content, "updated_at": g.updated_at.isoformat()}
            for g in guides
        ],
    }


class WebUpdateSystemEnabledRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/system")
def web_settings_system(req: WebUpdateSystemEnabledRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_system_enabled

    update_system_enabled(user["user_id"], req.enabled)
    return {"system_enabled": req.enabled}


class WebUpdateAutopilotRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/autopilot")
def web_settings_autopilot(req: WebUpdateAutopilotRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_autopilot

    update_autopilot(user["user_id"], req.enabled)
    return {"autopilot_enabled": req.enabled}


class WebUpdateSalesEmailRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/sales-emails")
def web_settings_sales_emails(req: WebUpdateSalesEmailRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_process_sales_emails

    update_process_sales_emails(user["user_id"], req.enabled)
    return {"process_sales_emails": req.enabled}


class WebUpdateBrandingRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/branding")
def web_settings_branding(req: WebUpdateBrandingRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_stash_branding

    update_stash_branding(user["user_id"], req.enabled)
    return {"stash_branding_enabled": req.enabled}


class WebUpdateReasoningEmailsRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/reasoning-emails")
def web_settings_reasoning_emails(req: WebUpdateReasoningEmailsRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_reasoning_emails_enabled

    update_reasoning_emails_enabled(user["user_id"], req.enabled)
    return {"reasoning_emails_enabled": req.enabled}


@app.get("/web/api/v1/calendars")
def web_list_calendars(user: dict = Depends(get_authenticated_user)):
    """List all Google calendars visible to the user, with selection state."""
    from scheduler.db import get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")

    creds = load_credentials(user["user_id"])
    calendar = CalendarClient(creds, config.stash_calendar_name)
    selected_ids = set(db_user.calendar_ids or [])

    all_cals = calendar.list_calendars()
    stash_id = calendar.get_or_create_stash_calendar()

    # Filter out the stash calendar — users shouldn't toggle it
    return [
        {**cal, "selected": cal["id"] in selected_ids}
        for cal in all_cals
        if cal["id"] != stash_id
    ]


class WebUpdateCalendarsRequest(BaseModel):
    calendar_ids: list[str]


@app.put("/web/api/v1/settings/calendars")
def web_settings_calendars(req: WebUpdateCalendarsRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import update_calendar_ids

    update_calendar_ids(user["user_id"], req.calendar_ids)
    return {"calendar_ids": req.calendar_ids}


class WebUpdateGuideRequest(BaseModel):
    content: str


@app.put("/web/api/v1/guides/{name}")
def web_guide_update(name: str, req: WebUpdateGuideRequest, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import upsert_guide

    guide = upsert_guide(user["user_id"], name, req.content)
    return {"name": guide.name, "content": guide.content, "updated_at": guide.updated_at.isoformat()}


@app.post("/web/api/v1/guides/{name}/regenerate")
def web_guide_regenerate(name: str, background_tasks: BackgroundTasks, user: dict = Depends(get_authenticated_user)):
    """Regenerate a single guide by re-running the appropriate agent."""
    if name not in ("scheduling_preferences", "email_style"):
        raise HTTPException(status_code=400, detail=f"Unknown guide: {name}")
    background_tasks.add_task(_run_guide_regeneration, user["user_id"], name)
    return {"status": "regenerating"}


def _run_guide_regeneration(user_id: str, guide_name: str) -> None:
    """Background task: re-run a single guide agent for a user."""
    import anyio

    from scheduler.guides.backends import LocalGuideBackend

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    calendar.get_or_create_stash_calendar()

    guide_backend = LocalGuideBackend(gmail, calendar, user_id=user_id)

    if guide_name == "scheduling_preferences":
        from scheduler.guides.preferences import run_preferences_agent

        anyio.run(run_preferences_agent, guide_backend)
    elif guide_name == "email_style":
        from scheduler.guides.style import run_style_agent

        anyio.run(run_style_agent, guide_backend)

    logger.info("guide_regeneration: completed %s for user=%s", guide_name, user_id)


@app.post("/web/api/v1/account/disconnect")
def web_account_disconnect(request: Request, user: dict = Depends(get_authenticated_user)):
    from scheduler.db import disconnect_user, get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    if db_user and db_user.google_refresh_token:
        import httpx

        try:
            httpx.post(
                "https://oauth2.googleapis.com/revoke",
                params={"token": db_user.google_refresh_token},
                headers={"Content-Type": "application/x-www-form-urlencoded"},
            )
        except Exception:
            logger.warning("Failed to revoke Google token for user=%s", user["user_id"])

    disconnect_user(user["user_id"])

    return JSONResponse({"status": "disconnected"})


@app.post("/api/v1/gmail/watch/renew")
def gmail_watch_renew():
    """Renew Gmail push notification watches for all users.

    Intended to be called by a daily cron job. No auth required since
    it only re-registers existing watches (idempotent and safe).
    """
    from scheduler.gmail.watch import renew_all_watches

    result = renew_all_watches()
    return result
