"""Control plane API — exposes Gmail and Calendar operations over HTTP.

We mean "control plane" in the following sense: https://browser-use.com/posts/two-ways-to-sandbox-agents

Runs in render. Holds Google OAuth tokens
and provides authenticated endpoints that the sandbox agent calls.

Session tokens are short-lived credentials that map to a user's Google
OAuth credentials. They are generated by the orchestrator (run_e2b.py)
and passed into the sandbox as an env var.
"""

import base64
import hashlib
import hmac
import json
import logging
import secrets
import time
import urllib.parse
from datetime import datetime

from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from pydantic import BaseModel

from scheduler.auth.google_auth import SCOPES, load_credentials
from scheduler.calendar.client import CalendarClient, Event
from scheduler.config import config
from scheduler.gmail.client import GmailClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title="Scheduler Control Plane")

# Allow the web frontend to call the control plane
app.add_middleware(
    CORSMiddleware,
    allow_origins=[config.web_app_url],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- Web auth helpers ---


def _sign_session(user_id: str, email: str) -> str:
    """Create an HMAC-signed session token encoding user_id and email."""
    payload = json.dumps({"user_id": user_id, "email": email})
    sig = hmac.new(config.session_secret.encode(), payload.encode(), hashlib.sha256).hexdigest()
    return base64.urlsafe_b64encode(f"{payload}|{sig}".encode()).decode()


def _verify_session(token: str) -> dict | None:
    """Verify and decode an HMAC-signed session token."""
    try:
        decoded = base64.urlsafe_b64decode(token).decode()
        payload, sig = decoded.rsplit("|", 1)
        expected = hmac.new(config.session_secret.encode(), payload.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(sig, expected):
            return None
        return json.loads(payload)
    except Exception:
        return None

# --- Web OAuth routes ---

# Temporary store for OAuth state tokens (state -> timestamp)
_oauth_states: dict[str, float] = {}


@app.get("/auth/google")
def auth_google_redirect(signin: str | None = None):
    """Redirect the user to Google's OAuth consent screen.

    If signin=1, uses prompt=select_account (returning users just pick their account).
    Otherwise, uses prompt=consent (new users grant full permissions).
    """
    is_signin = signin == "1"
    state_data = f"{secrets.token_urlsafe(32)}|signin={1 if is_signin else 0}"
    _oauth_states[state_data] = time.time()

    params = {
        "client_id": config.google_client_id,
        "redirect_uri": config.google_web_redirect_uri,
        "response_type": "code",
        "scope": " ".join(SCOPES),
        "access_type": "offline",
        "prompt": "select_account" if is_signin else "consent",
        "state": state_data,
    }
    url = f"https://accounts.google.com/o/oauth2/v2/auth?{urllib.parse.urlencode(params)}"
    return RedirectResponse(url)


@app.get("/")
def root_callback(code: str | None = None, state: str | None = None, error: str | None = None):
    """Handle the OAuth callback at the root path (Google redirects to http://localhost:8080).

    If no OAuth query params are present, returns a simple health check.
    """
    if not code and not state and not error:
        return {"status": "ok", "service": "scheduler-control-plane"}
    return auth_google_callback(code=code, state=state, error=error)


def auth_google_callback(code: str | None = None, state: str | None = None, error: str | None = None):
    """Handle the OAuth callback from Google.

    Exchanges the authorization code for tokens, upserts the user in the
    database, and redirects to the web app with a signed session cookie.

    Supports two modes based on state:
    - Sign-up (default): expects refresh_token, upserts user, runs full onboarding
    - Sign-in (state contains signin=1): no refresh_token needed, looks up existing user
    """
    if error:
        return RedirectResponse(f"{config.web_app_url}?error={error}")

    if not code or not state:
        return RedirectResponse(f"{config.web_app_url}?error=missing_params")

    # Validate state
    issued_at = _oauth_states.pop(state, None)
    if not issued_at or (time.time() - issued_at > 600):
        return RedirectResponse(f"{config.web_app_url}?error=invalid_state")

    is_signin = state.endswith("|signin=1")

    # Exchange authorization code for tokens
    import httpx

    token_response = httpx.post(
        "https://oauth2.googleapis.com/token",
        data={
            "code": code,
            "client_id": config.google_client_id,
            "client_secret": config.google_client_secret,
            "redirect_uri": config.google_web_redirect_uri,
            "grant_type": "authorization_code",
        },
    )

    if token_response.status_code != 200:
        logger.error("OAuth token exchange failed: %s", token_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=token_exchange_failed")

    tokens = token_response.json()
    access_token = tokens["access_token"]
    refresh_token = tokens.get("refresh_token")

    # Get user's email from Google
    userinfo_response = httpx.get(
        "https://www.googleapis.com/oauth2/v2/userinfo",
        headers={"Authorization": f"Bearer {access_token}"},
    )

    if userinfo_response.status_code != 200:
        logger.error("Userinfo request failed: status=%s body=%s", userinfo_response.status_code, userinfo_response.text)
        return RedirectResponse(f"{config.web_app_url}?error=userinfo_failed")

    email = userinfo_response.json().get("email")
    if not email:
        return RedirectResponse(f"{config.web_app_url}?error=no_email")

    from scheduler.db import get_guides_for_user, get_user_by_email, upsert_user

    if refresh_token:
        # Sign-up flow (or sign-in that happened to return a refresh token)
        expires_in = tokens.get("expires_in")
        expires_at = None
        if expires_in:
            from datetime import timedelta
            expires_at = datetime.now() + timedelta(seconds=expires_in)

        user = upsert_user(
            email=email,
            google_refresh_token=refresh_token,
            google_access_token=access_token,
            access_token_expires_at=expires_at,
        )
    else:
        # Sign-in flow: no refresh token, look up existing user
        user = get_user_by_email(email)
        if not user:
            logger.warning("sign-in attempt for unknown user: %s", email)
            return RedirectResponse(f"{config.web_app_url}?error=account_not_found")

    # Determine if user is already onboarded
    guides = get_guides_for_user(str(user.id))
    guide_names = {g.name for g in guides}
    is_onboarded = "scheduling_preferences" in guide_names and "email_style" in guide_names

    from starlette.background import BackgroundTask

    if is_onboarded:
        # Returning user: just renew Gmail watch, redirect to settings
        logger.info("sign-in: returning user=%s, renewing gmail watch", user.id)
        background = BackgroundTask(_renew_gmail_watch, str(user.id))
        redirect_url = f"{config.web_app_url}/settings"
    else:
        # New user: run full onboarding, redirect to onboarding
        logger.info("onboarding: starting all agents for user=%s after OAuth", user.id)
        background = BackgroundTask(_run_onboarding_all, str(user.id))
        redirect_url = f"{config.web_app_url}/onboarding"

    # Create signed session and redirect to web app
    session_token = _sign_session(str(user.id), email)
    response = RedirectResponse(redirect_url, background=background)
    response.set_cookie(
        key="session",
        value=session_token,
        httponly=True,
        secure=config.web_app_url.startswith("https"),
        samesite="lax",
        max_age=60 * 60 * 24 * 365 * 10,  # 10 years
        path="/",
    )
    return response


def get_web_session(request: Request) -> dict:
    """Validate the session cookie from the web app."""
    session_cookie = request.cookies.get("session")
    if not session_cookie:
        raise HTTPException(status_code=401, detail="Not authenticated")
    payload = _verify_session(session_cookie)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid session")
    return payload


@app.get("/auth/me")
def auth_me(session: dict = Depends(get_web_session)):
    """Return the current user's info from the session cookie."""
    return {"user_id": session["user_id"], "email": session["email"]}


# --- Session store ---

sessions: dict[str, dict] = {}


def register_session(session_token: str, user_id: str) -> None:
    """Register a session with Google credentials for a user.

    Loads credentials from the database if DATABASE_URL is set and the user
    exists. Falls back to local OAuth flow (token.json) for development.
    """
    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    calendar.get_or_create_stash_calendar()

    sessions[session_token] = {
        "user_id": user_id,
        "gmail": gmail,
        "calendar": calendar,
        "created_at": time.time(),
    }



def get_session(authorization: str = Header()) -> dict:
    """Validate the session token from the Authorization header."""
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Invalid authorization header")

    token = authorization.removeprefix("Bearer ")
    session = sessions.get(token)
    if not session:
        raise HTTPException(status_code=401, detail="Invalid or expired session token")

    return session


# --- Serialization helpers ---


def _serialize_email(email) -> dict:
    return {
        "id": email.id,
        "thread_id": email.thread_id,
        "sender": email.sender,
        "recipient": email.recipient,
        "subject": email.subject,
        "body": email.body,
        "date": email.date.isoformat(),
        "snippet": email.snippet,
    }


def _serialize_event(event) -> dict:
    return {
        "id": event.id,
        "summary": event.summary,
        "start": event.start.isoformat(),
        "end": event.end.isoformat(),
        "description": event.description,
    }


# --- Request models ---


class SearchEmailsRequest(BaseModel):
    query: str
    max_results: int = 50


class CreateDraftRequest(BaseModel):
    thread_id: str
    to: str
    subject: str
    body: str


class GetEventsRequest(BaseModel):
    start_date: str
    end_date: str
    include_primary: bool = True


class FindEventRequest(BaseModel):
    summary: str
    start_date: str
    end_date: str


class AddEventRequest(BaseModel):
    summary: str
    start: str
    end: str
    description: str = ""


class UpdateBrandingRequest(BaseModel):
    enabled: bool


class UpdateAutopilotRequest(BaseModel):
    enabled: bool


class UpdateSystemEnabledRequest(BaseModel):
    enabled: bool


class WriteGuideRequest(BaseModel):
    name: str
    content: str


# --- Gmail routes ---


@app.post("/api/v1/gmail/search")
def gmail_search(req: SearchEmailsRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    emails = gmail.search(query=req.query, max_results=req.max_results)
    return {"emails": [_serialize_email(e) for e in emails]}


@app.get("/api/v1/gmail/thread/{thread_id}")
def gmail_thread(thread_id: str, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    messages = gmail.get_thread(thread_id)
    return {"messages": [_serialize_email(e) for e in messages]}


@app.post("/api/v1/gmail/draft")
def gmail_draft(req: CreateDraftRequest, session: dict = Depends(get_session)):
    gmail: GmailClient = session["gmail"]
    draft_id = gmail.create_draft(
        thread_id=req.thread_id, to=req.to, subject=req.subject, body=req.body
    )
    return {"draft_id": draft_id}


# --- Calendar routes ---


@app.post("/api/v1/calendar/events")
def calendar_events(req: GetEventsRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    events = calendar.get_all_events(
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
        include_primary=req.include_primary,
    )
    return {"events": [_serialize_event(e) for e in events]}


@app.post("/api/v1/calendar/find")
def calendar_find(req: FindEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = calendar.find_event(
        summary=req.summary,
        time_min=datetime.fromisoformat(req.start_date),
        time_max=datetime.fromisoformat(req.end_date),
    )
    if event:
        return {"exists": True, "event": _serialize_event(event)}
    return {"exists": False, "event": None}


@app.post("/api/v1/calendar/add")
def calendar_add(req: AddEventRequest, session: dict = Depends(get_session)):
    calendar: CalendarClient = session["calendar"]
    event = Event(
        id=None,
        summary=req.summary,
        start=datetime.fromisoformat(req.start),
        end=datetime.fromisoformat(req.end),
        description=req.description,
        source="gmail",
    )
    event_id = calendar.add_event(event)
    return {"event_id": event_id, "status": "created"}


# --- Settings routes ---


@app.get("/api/v1/settings/branding")
def settings_branding_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"stash_branding_enabled": user.stash_branding_enabled}


@app.put("/api/v1/settings/branding")
def settings_branding_put(req: UpdateBrandingRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_stash_branding

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_stash_branding(session["user_id"], req.enabled)
    return {"stash_branding_enabled": req.enabled}


@app.get("/api/v1/settings/autopilot")
def settings_autopilot_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"autopilot_enabled": user.autopilot_enabled}


@app.put("/api/v1/settings/autopilot")
def settings_autopilot_put(req: UpdateAutopilotRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_autopilot

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_autopilot(session["user_id"], req.enabled)
    return {"autopilot_enabled": req.enabled}


@app.get("/api/v1/settings/system")
def settings_system_get(session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return {"system_enabled": user.system_enabled}


@app.put("/api/v1/settings/system")
def settings_system_put(req: UpdateSystemEnabledRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_user_by_id, update_system_enabled

    user = get_user_by_id(session["user_id"])
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    update_system_enabled(session["user_id"], req.enabled)
    return {"system_enabled": req.enabled}


# --- Guide routes ---


class ReadGuideRequest(BaseModel):
    name: str


@app.post("/api/v1/guides/write")
def guides_write(req: WriteGuideRequest, session: dict = Depends(get_session)):
    from scheduler.guides import save_guide

    user_id = session["user_id"]
    save_guide(name=req.name, content=req.content, user_id=user_id)
    return {"status": "written"}


@app.post("/api/v1/guides/read")
def guides_read(req: ReadGuideRequest, session: dict = Depends(get_session)):
    from scheduler.db import get_guide

    user_id = session["user_id"]
    guide = get_guide(user_id=user_id, name=req.name)
    if not guide:
        raise HTTPException(status_code=404, detail=f"Guide '{req.name}' not found")
    return {"name": guide.name, "content": guide.content, "updated_at": guide.updated_at.isoformat()}


# --- Onboarding ---


def _renew_gmail_watch(user_id: str) -> None:
    """Background task: renew Gmail watch for a returning user."""
    from scheduler.gmail.watch import setup_gmail_watch

    try:
        setup_gmail_watch(user_id)
        logger.info("sign-in: gmail watch renewed for user=%s", user_id)
    except Exception:
        logger.exception("sign-in: failed to renew gmail watch for user=%s", user_id)


def _run_onboarding_all(user_id: str) -> None:
    """Background task: run backfill + both guide-writer agents for a user, then set up Gmail watch."""
    import anyio
    from scheduler.gmail.watch import setup_gmail_watch
    from scheduler.guides.backends import LocalGuideBackend
    from scheduler.guides.preferences import run_preferences_agent
    from scheduler.guides.style import run_style_agent
    from scheduler.onboarding.agent import _run_onboarding_async as _run_backfill
    from scheduler.onboarding.backends import LocalBackend

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    calendar.get_or_create_stash_calendar()

    guide_backend = LocalGuideBackend(gmail, calendar, user_id=user_id)
    onboarding_backend = LocalBackend(gmail, calendar)

    async def _run():
        async with anyio.create_task_group() as tg:
            tg.start_soon(_run_backfill, onboarding_backend, config.onboarding_lookback_days)
            tg.start_soon(run_preferences_agent, guide_backend)
            tg.start_soon(run_style_agent, guide_backend)

    anyio.run(_run)

    # Set up Gmail watch so incoming emails are processed
    try:
        setup_gmail_watch(user_id)
        logger.info("onboarding: gmail watch set up for user=%s", user_id)
    except Exception:
        logger.exception("onboarding: failed to set up gmail watch for user=%s", user_id)


@app.post("/api/v1/onboarding/run")
def onboarding_run(request: Request, background_tasks: BackgroundTasks):
    """Kick off the style + preferences guide agents for this user."""
    session = get_web_session(request)
    user_id = session["user_id"]
    logger.info("onboarding: starting all agents for user=%s", user_id)
    background_tasks.add_task(_run_onboarding_all, user_id)
    return {"status": "started"}


# --- Gmail webhook ---

# Per-user sets of recently processed message IDs to avoid duplicate drafts.
# Bounded to last 200 IDs per user to avoid unbounded growth.
_processed_messages: dict[str, set[str]] = {}
_PROCESSED_MAX = 200


def _mark_processed(user_id: str, message_id: str) -> bool:
    """Mark a message as processed. Returns True if it was already processed."""
    seen = _processed_messages.setdefault(user_id, set())
    if message_id in seen:
        return True
    seen.add(message_id)
    if len(seen) > _PROCESSED_MAX:
        # Evict oldest entries (sets are unordered, but this is good enough)
        to_remove = len(seen) - _PROCESSED_MAX
        for _ in range(to_remove):
            seen.pop()
    return False


def _process_new_messages(user_id: str, email_address: str, history_id: str) -> None:
    """Background task: fetch new messages since last history ID and log them.

    This is the hook point where the classifier agent will be triggered.
    """
    from scheduler.db import get_user_by_id, update_gmail_history_id

    user = get_user_by_id(user_id)
    if not user:
        return
    if not user.system_enabled:
        logger.info("gmail_webhook: system disabled for user=%s, skipping", email_address)
        return
    if not user.gmail_history_id:
        # First notification — just store the history ID baseline
        update_gmail_history_id(user_id, history_id)
        logger.info("gmail_webhook: stored initial history_id=%s for user=%s", history_id, email_address)
        return

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)

    try:
        new_message_ids = gmail.get_history(user.gmail_history_id)
    except Exception:
        # History ID may be too old (> 7 days). Reset baseline.
        logger.warning("gmail_webhook: history expired for user=%s, resetting", email_address)
        update_gmail_history_id(user_id, history_id)
        return

    update_gmail_history_id(user_id, history_id)

    if not new_message_ids:
        return

    logger.info(
        "gmail_webhook: %d new message(s) for user=%s: %s",
        len(new_message_ids),
        email_address,
        new_message_ids,
    )

    from scheduler.classifier.intent import SchedulingIntent, classify_email
    from scheduler.drafts.composer import DraftComposer

    calendar = CalendarClient(creds, config.stash_calendar_name)

    for message_id in new_message_ids:
        if _mark_processed(user_id, message_id):
            logger.info("gmail_webhook: message %s already processed, skipping", message_id)
            continue

        try:
            email = gmail.get_email(message_id)

            # For messages sent by the user: check if this is a sent invite draft
            if email.sender and email_address in email.sender:
                from scheduler.db import delete_pending_invite, get_pending_invite_by_thread

                invite = get_pending_invite_by_thread(user_id, email.thread_id)
                if invite:
                    # Classify whether the sent message still confirms the meeting
                    from scheduler.classifier.intent import classify_sent_message_confirms_invite

                    confirms = classify_sent_message_confirms_invite(email.body, invite.event_summary)
                    if not confirms:
                        logger.info(
                            "gmail_webhook: message %s in thread %s does not confirm the meeting, deleting pending invite",
                            message_id,
                            email.thread_id,
                        )
                        delete_pending_invite(str(invite.id))
                    else:
                        logger.info(
                            "gmail_webhook: message %s confirms invite for thread %s, creating calendar event",
                            message_id,
                            email.thread_id,
                        )
                        try:
                            event_id = calendar.create_invite_event(
                                summary=invite.event_summary,
                                start=invite.event_start,
                                end=invite.event_end,
                                attendee_email=invite.attendee_email,
                                add_google_meet=invite.add_google_meet,
                            )
                            delete_pending_invite(str(invite.id))
                            logger.info("gmail_webhook: created invite event %s for thread %s", event_id, email.thread_id)
                        except Exception:
                            logger.exception("gmail_webhook: failed to create invite event for thread %s", email.thread_id)
                else:
                    logger.info("gmail_webhook: message %s is from the user, skipping", message_id)
                continue

            classification = classify_email(email.subject, email.body, email.sender)

            if classification.intent == SchedulingIntent.NOT_SCHEDULING:
                logger.info("gmail_webhook: message %s is not scheduling-related, skipping", message_id)
                continue

            logger.info(
                "gmail_webhook: message %s classified as %s (confidence=%.2f), composing draft",
                message_id,
                classification.intent.value,
                classification.confidence,
            )

            composer = DraftComposer(gmail, calendar, user_id, autopilot=user.autopilot_enabled)
            draft_id = composer.compose_and_create_draft(email, classification)
            if draft_id is None:
                logger.info("gmail_webhook: thread for message %s already resolved, no draft created", message_id)
                continue
            logger.info("gmail_webhook: created draft %s for message %s", draft_id, message_id)

        except Exception:
            logger.exception("gmail_webhook: failed to process message %s for user=%s", message_id, email_address)


@app.post("/webhooks/gmail")
async def gmail_webhook(request: Request, background_tasks: BackgroundTasks):
    """Receive Gmail push notifications via Google Cloud Pub/Sub.

    Google sends a POST with a Pub/Sub message whose data is a base64-encoded
    JSON object containing the user's email address and the latest historyId.

    This endpoint is unauthenticated — Google does not send a session token.
    We look up the user by email address instead.
    """
    from scheduler.db import get_user_by_email

    body = await request.json()
    message = body.get("message", {})
    data_b64 = message.get("data", "")

    if not data_b64:
        raise HTTPException(status_code=400, detail="Missing message data")

    try:
        payload = json.loads(base64.urlsafe_b64decode(data_b64))
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid message data")

    email_address = payload.get("emailAddress")
    history_id = str(payload.get("historyId", ""))

    if not email_address or not history_id:
        raise HTTPException(status_code=400, detail="Missing emailAddress or historyId")

    user = get_user_by_email(email_address)
    if not user:
        logger.warning("gmail_webhook: unknown email %s", email_address)
        # Return 200 so Pub/Sub doesn't retry for unknown users
        return {"status": "ignored", "reason": "unknown user"}

    background_tasks.add_task(_process_new_messages, str(user.id), email_address, history_id)

    return {"status": "ok"}


# --- Web API routes (cookie auth) ---


def get_web_user(request: Request) -> dict:
    """Validate the session cookie and return the user payload."""
    session_cookie = request.cookies.get("session")
    if not session_cookie:
        raise HTTPException(status_code=401, detail="Not authenticated")
    payload = _verify_session(session_cookie)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid session")
    return payload


@app.get("/web/api/v1/onboarding/status")
def web_onboarding_status(user: dict = Depends(get_web_user)):
    from scheduler.db import get_guides_for_user, get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    connected = db_user is not None and db_user.google_refresh_token is not None

    if connected:
        guides = get_guides_for_user(user["user_id"])
        guide_names = {g.name for g in guides}
        ready = "scheduling_preferences" in guide_names and "email_style" in guide_names
    else:
        ready = False

    return {"ready": ready, "connected": connected}


@app.get("/web/api/v1/settings")
def web_settings_get(user: dict = Depends(get_web_user)):
    from scheduler.db import get_guides_for_user, get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")

    guides = get_guides_for_user(user["user_id"])

    return {
        "system_enabled": db_user.system_enabled,
        "autopilot_enabled": db_user.autopilot_enabled,
        "stash_branding_enabled": db_user.stash_branding_enabled,
        "stash_calendar_id": db_user.stash_calendar_id,
        "guides": [
            {"name": g.name, "content": g.content, "updated_at": g.updated_at.isoformat()}
            for g in guides
        ],
    }


class WebUpdateSystemEnabledRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/system")
def web_settings_system(req: WebUpdateSystemEnabledRequest, user: dict = Depends(get_web_user)):
    from scheduler.db import update_system_enabled

    update_system_enabled(user["user_id"], req.enabled)
    return {"system_enabled": req.enabled}


class WebUpdateAutopilotRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/autopilot")
def web_settings_autopilot(req: WebUpdateAutopilotRequest, user: dict = Depends(get_web_user)):
    from scheduler.db import update_autopilot

    update_autopilot(user["user_id"], req.enabled)
    return {"autopilot_enabled": req.enabled}


class WebUpdateBrandingRequest(BaseModel):
    enabled: bool


@app.put("/web/api/v1/settings/branding")
def web_settings_branding(req: WebUpdateBrandingRequest, user: dict = Depends(get_web_user)):
    from scheduler.db import update_stash_branding

    update_stash_branding(user["user_id"], req.enabled)
    return {"stash_branding_enabled": req.enabled}


class WebUpdateGuideRequest(BaseModel):
    content: str


@app.put("/web/api/v1/guides/{name}")
def web_guide_update(name: str, req: WebUpdateGuideRequest, user: dict = Depends(get_web_user)):
    from scheduler.db import upsert_guide

    guide = upsert_guide(user["user_id"], name, req.content)
    return {"name": guide.name, "content": guide.content, "updated_at": guide.updated_at.isoformat()}


@app.post("/web/api/v1/guides/{name}/regenerate")
def web_guide_regenerate(name: str, background_tasks: BackgroundTasks, user: dict = Depends(get_web_user)):
    """Regenerate a single guide by re-running the appropriate agent."""
    if name not in ("scheduling_preferences", "email_style"):
        raise HTTPException(status_code=400, detail=f"Unknown guide: {name}")
    background_tasks.add_task(_run_guide_regeneration, user["user_id"], name)
    return {"status": "regenerating"}


def _run_guide_regeneration(user_id: str, guide_name: str) -> None:
    """Background task: re-run a single guide agent for a user."""
    import anyio

    from scheduler.guides.backends import LocalGuideBackend

    creds = load_credentials(user_id)
    gmail = GmailClient(creds)
    calendar = CalendarClient(creds, config.stash_calendar_name)
    calendar.get_or_create_stash_calendar()

    guide_backend = LocalGuideBackend(gmail, calendar, user_id=user_id)

    if guide_name == "scheduling_preferences":
        from scheduler.guides.preferences import run_preferences_agent

        anyio.run(run_preferences_agent, guide_backend)
    elif guide_name == "email_style":
        from scheduler.guides.style import run_style_agent

        anyio.run(run_style_agent, guide_backend)

    logger.info("guide_regeneration: completed %s for user=%s", guide_name, user_id)


@app.post("/web/api/v1/account/disconnect")
def web_account_disconnect(request: Request, user: dict = Depends(get_web_user)):
    from scheduler.db import disconnect_user, get_user_by_id

    db_user = get_user_by_id(user["user_id"])
    if db_user and db_user.google_refresh_token:
        import httpx

        try:
            httpx.post(
                "https://oauth2.googleapis.com/revoke",
                params={"token": db_user.google_refresh_token},
                headers={"Content-Type": "application/x-www-form-urlencoded"},
            )
        except Exception:
            logger.warning("Failed to revoke Google token for user=%s", user["user_id"])

    disconnect_user(user["user_id"])

    return JSONResponse({"status": "disconnected"})


@app.post("/api/v1/gmail/watch/renew")
def gmail_watch_renew():
    """Renew Gmail push notification watches for all users.

    Intended to be called by a daily cron job. No auth required since
    it only re-registers existing watches (idempotent and safe).
    """
    from scheduler.gmail.watch import renew_all_watches

    result = renew_all_watches()
    return result
